### ISSUE TITLE
Hole

### ISSUE THREAD

**Issue by NiteCyper** [Zren/ResizeYoutubePlayerToWindowSize#10]
Now there's a black box where the player used to be whereas the video is at the top of the page (as this script intends).

**Comment by Zren** [comment]
Thanks for reporting. Fixed in v58.

**Comment by NiteCyper** [comment]
You ... I like you. Anything you want me to do to help promote your work?

**Comment by Zren** [comment]
Nah. It's cool. The script apparently got [Lifehackered](http://lifehacker.com/resize-youtubes-player-to-fit-your-browser-window-493160000) awhile back so it's already gotten it's 10 seconds of internet fame.
