### ISSUE TITLE
Black Screen on v. 61 with sound (no images)

### ISSUE THREAD

**Issue by UNREALWINS** [Zren/ResizeYoutubePlayerToWindowSize#11]
Here in my FF when I updated to the v61 the video screen is all black and only plays the sound. There's no image.

**Comment by Zren** [comment]
Does YouTube work if you disable the script?

**Comment by UNREALWINS** [comment]
Yes, works with the script disabled.

**Comment by UNREALWINS** [comment]
Oh, I found the problem. The script have conflict with the youtube center developer build 507. I disabled the youtube center and your script works.

**Comment by Zren** [comment]
K. Saw someone who asked about the same issue without my script so was just checking of YouTube broke but guess not.

I'll fix when I get

**Comment by Zren** [comment]
... Home. Bleh.

**Comment by UNREALWINS** [comment]
Get the youtube center developer. Updated a lot: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by Zren** [comment]
Ah, Youtube released a new player.

https://www.youtube.com/testtube

Fixed the height issue on one of the new elements in v62. I'll release another version once I find where the stupid control bar width function is.

**Comment by UNREALWINS** [comment]
Thanks for the update! Now is ok here! Thanks a lot!

**Comment by Zren** [comment]
v63 fixes the control bar width and removes the transition on the top navigation bar I noticed with YT Center enabled.
