### ISSUE TITLE
Time line width shrunk by 50%

### ISSUE THREAD

**Issue by NiteCyper** [Zren/ResizeYoutubePlayerToWindowSize#12]
Time line, playback bar, video progress meter, whatever it's called, now it's only spanning half of the width of the video box area. Otherwise, it's fine; it is not as though it is only showing half. It is as if the visual time line has been shrunk down by 50%.

**Comment by Zren** [comment]
Bleh. Having multiple versions of the player going around is annoying. I'm guessing you're still using the old one?

Tell me if v65 fixes it for you.

**Comment by NiteCyper** [comment]
v65 does not fix it for me.

**Comment by Zren** [comment]
New or old player? If you're using the old player, does turning on the new one fix it?

https://www.youtube.com/testtube

**Comment by NiteCyper** [comment]
Old player. Turning on the new one does not fix it.

Date: Thu, 28 May 2015 23:25:13 -0700

**Comment by Zren** [comment]
Aight. Guess that'll work for now till it breaks again.

**Comment by fent** [comment]
This was an issue for me on the old player. Didn't know about the new player but it works there, and it looks better thanks! O_O

**Comment by NiteCyper** [comment]
Issue now affects new player.

**Comment by Zren** [comment]
It still works fine for me on chrome and firefox. Any errors in the console? Does turning off the new player work? Does turning it back on afterwards work?

**Comment by NiteCyper** [comment]
Console:

"[ytwp] " "Could not hook yt.pubsub" TypeError: uw.yt is undefined
Stack trace:
ytwp.registerYoutubePubSubListeners@file:///C:/Users/NiteCyper/AppData/Roaming/Mozilla/Firefox/Profiles/lzuiayfw.default/gm_scripts/Resize_YT_To_Window_Size/Resize_YT_To_Window_Size.user.js:637:13
ytwp.registerYoutubeListeners@file:///C:/Users/NiteCyper/AppData/Roaming/Mozilla/Firefox/Profiles/lzuiayfw.default/gm_scripts/Resize_YT_To_Window_Size/Resize_YT_To_Window_Size.user.js:630:9
ytwp.main@file:///C:/Users/NiteCyper/AppData/Roaming/Mozilla/Firefox/Profiles/lzuiayfw.default/gm_scripts/Resize_YT_To_Window_Size/Resize_YT_To_Window_Size.user.js:643:13
 Resize_YT_To_Window_Size.user.js:173:40

Toggling between the new and old players doesn't fix it. Also, this time it's not half but 2/3.

Date: Fri, 17 Jul 2015 20:13:52 -0700

**Comment by fent** [comment]
This was happening to me yesterday but it's fine right now.

**Comment by Zren** [comment]
@NiteCyper Just checking in to see if Youtube fixed itself. If not, try:

* Logging out and checking.
* Clearing your youtube cookies? Lock icon in address bar > More Information > View Cookies > Remove All ![](http://i.imgur.com/XPZJLMB.png)

**Comment by NiteCyper** [comment]
It hasn't fixed itself. Logging out did not fix it. Clearing cookies did not fix it.

**Comment by Zren** [comment]
What's the value of your `VISITOR_INFO1_LIVE` cookie? For me there's two, one empty, but the other is `IBLiGRIk3nI`.

![](http://i.imgur.com/jj3A2FQ.png)

**Comment by NiteCyper** [comment]
"KePgnRMKJtc". I only have one.

**Comment by Zren** [comment]
K it's not youtube. What version of operating system +  firefox + greasemonkey?

**Comment by NiteCyper** [comment]
I had Greasemonkey 1.9. Updating it fixed it.
