### ISSUE TITLE
player incorrectly positioned if window is too small

### ISSUE THREAD

**Issue by fent** [Zren/ResizeYoutubePlayerToWindowSize#13]
![screen shot 2015-06-13 at 5 41 00 pm](https://cloud.githubusercontent.com/assets/933490/8146088/e2a68adc-11f3-11e5-939f-96dbb0013415.png)

Seems to happen with smaller windows, once I resize the window to a bigger size, it's fixed. But if I resize it to small, it happens again.

**Comment by darius07** [comment]
I also experience this issue, Youtube's Defaul/Cinema seems to help a little.

**Comment by Zren** [comment]
Thanks for reporting. Didn't realize there were xs sized media queries (or javascript or whatever).

**Comment by fent** [comment]
Thanks for the fast response.
