### ISSUE TITLE
Fail to resize youtube live streams (Youtube Gaming)

### ISSUE THREAD

**Issue by fhoshino** [Zren/ResizeYoutubePlayerToWindowSize#15]
A youtube gaming live stream does not resize to window size.

**Comment by Zren** [comment]
https://gaming.youtube,com

Do to the way the layout is done, there honestly isn't a good way to style this.

![image](https://cloud.githubusercontent.com/assets/416367/11458842/80c48d14-9696-11e5-8a7b-9c9e0f074bbb.png)

I'd have to hide both the naviagtion bar and the sidebar most likely, so this would need to be a toggle'd look through a button.

Basically, it's not easy and might not even add it.

**Comment by Aidoboy** [comment]
What about regular YouTube Gaming videos?

**Comment by Zren** [comment]
Huh? I won't be doing anything on the https://gaming.youtube.com domain.

**Comment by Aidoboy** [comment]
Darn, ok.

**Comment by Zren** [comment]
I assume they shut it down? It redirects to https://www.youtube.com/gaming

Yep happened in 2018: https://arstechnica.com/gadgets/2019/05/googles-killing-the-youtube-gaming-app-this-week/
