### ISSUE TITLE
Breaks ad skips

### ISSUE THREAD

**Issue by arantius** [Zren/ResizeYoutubePlayerToWindowSize#16]
When I enable this script, all ads play in full, the "skip this ad" button never appears.

**Comment by Zren** [comment]
Thanks for reporting as I'd never notice this myself with ad blocking stuff. Looks like I just need to add `top:0;` to `.html5-video-player .ad-container-single-media-element-annotations`. The rule sounds like there might be other versions of the player that use different classes. Hmmm. Maybe the "3D Mode" which lines two videos up side by side. I'll need to look into that.

Anyways v74 fixes that.

**Comment by arantius** [comment]
Thanks for the super quick fix!  Confirmed.
