### ISSUE TITLE
Half size bar :(

### ISSUE THREAD

**Issue by riccardosimo** [Zren/ResizeYoutubePlayerToWindowSize#18]
Can you fix it please?  http://imgur.com/klUehCz

**Comment by Zren** [comment]
v79 should fix it (temporarily). I'll push a proper fix that won't break so easily in a bit.

**Comment by riccardosimo** [comment]
love you <3

**Comment by riccardosimo** [comment]
nooooooooo still the same error ç____ç

**Comment by Zren** [comment]
Reopen/create anew if v85 doesn't fix this, since I just updated the fix tonight.
