### ISSUE TITLE
Still Half size bar :(

### ISSUE THREAD

**Issue by riccardosimo** [Zren/ResizeYoutubePlayerToWindowSize#19]

**Comment by Zren** [comment]
Is this still an issue? I finally got around to testing this on a Windows machine (Just install Kubuntu) and it seems to be working?

**Comment by riccardosimo** [comment]
`http://postimg.org/image/r6ov0jnf1/full/`

**Comment by Zren** [comment]
When does it happen? After a few videos autoplay, or on the first video? Does clicking it fix it?

**Comment by riccardosimo** [comment]
it happens with every video i see.. and yes.. if i click it fix it
