### ISSUE TITLE
Half size bar

### ISSUE THREAD

**Issue by riccardosimo** [Zren/ResizeYoutubePlayerToWindowSize#20]
https://s8.postimg.org/b0ebiw11h/Cattura.jpg

**Comment by stoatally** [comment]
Happens for me on every video, pausing and resuming the video fixes it.

**Comment by Zren** [comment]
Reopen/create anew if v85 doesn't fix this, since I just updated the fix tonight.

**Comment by SolarPolarMan** [comment]
I had this and you just need to hit the View Toggle button in the bottom right.
