### ISSUE TITLE
masthead-positioner-height-offset has wrong height after closing share thing with x

### ISSUE THREAD

**Issue by roy192** [Zren/ResizeYoutubePlayerToWindowSize#23]
when I open the share thing, and then close it with the x in the top right, I get a lot of empty space above the title of the video (see images below). Strangely enough, this doesn't happen when I close it by pressing that share button again.

I've tested it with firefox 48.0.2 and chrome 48.0.2564.116 both with no other user scripts, or user styles enabled.

![open](https://cloud.githubusercontent.com/assets/6928846/18225037/ca4741b4-71e9-11e6-81ef-a663f1b91dcd.png)
![close](https://cloud.githubusercontent.com/assets/6928846/18225038/ca626e26-71e9-11e6-8694-e82b2cbb2518.png)
![space](https://cloud.githubusercontent.com/assets/6928846/18225039/ca86b81c-71e9-11e6-9794-8e2937f8fac7.png)

**Comment by Zren** [comment]
Thanks for the bug report (with pictures)! Should be fixed in v86. I just copied Youtube's normal CSS rules for the element and tossed in some `!importants` since it seems closing that button adds changes the height with javascript...

**Comment by roy192** [comment]
It seems to work, but there are still two little problems. The first one is when youtube wants to display some message about privacy (when you're not logged in or in private browsing mode), which makes the element a bit taller than normal (106px instead of 50px). So the title of the video is now hidden.
![privacy](https://cloud.githubusercontent.com/assets/6928846/18226339/f1e5f7a6-7207-11e6-9155-114b7fd5a31a.png)
The other problem is a bit worse, when I navigate away from the video (to my subscriptions for example), then, the empty space is back. The css rule seems to only work when on a page with an actual video.

**Comment by Zren** [comment]
Bleh. I can manually remove the `el.style.height` after it's changed, but it also fucks with the menu/guide's position. The extra space is based on the position from the top of the window (aka how much of the video is shown).

![](https://i.imgur.com/QW0oaWA.png)

I'm going to revert my fix since it causes more problems then it helps. Gonna think on a way to hack this is way more trouble than it's worth. v87 is going to have the following which will hide the empty space (but not fix the guide). Tell me if it works with the "Private Bar" thing since I don't have that.

```javascript
function observe(selector, config, callback) {
	var observer = new MutationObserver(function(mutations) {
		mutations.forEach(function(mutation){
			callback(mutation);
		});
	});
	var target = document.querySelector(selector);
	observer.observe(target, config);
	return observer;
}

observe('#masthead-positioner-height-offset', {
	attributes: true,
}, function(mutation) {
	console.log(mutation.type, mutation)
	if (mutation.attributeName === 'style') {
		var el = mutation.target;
		if (el.style.height) { // != ""
			setTimeout(function(){
				el.style.height = ""
			}, 0);
		}
		
	}
});
```

**Comment by Zren** [comment]
v87 is live, I also fixed the guide's positioning. Tell me if you notice anything else.
