### ISSUE TITLE
No longer resizing YouTube videos

### ISSUE THREAD

**Issue by HenryB96** [Zren/ResizeYoutubePlayerToWindowSize#24]
As of today the script doesn't appear to be resizing YouTube videos anymore.

**Comment by Zren** [comment]
Did they finally start shipping the Material Design update? Bleh, guess I gotta fix this. Until it's fixed, either don't use the script or hit the little icon in the bottom left (with the script off) to go back to the old youtube layout.

![](https://i.imgur.com/2Z7qWq1.png)

I've gotten it to work with some extra CSS, I just need to do a lot more testing and convert it to JS so it doesn't break for everyone else.

![](https://i.imgur.com/h3qdeZC.png)

**Comment by Zren** [comment]
If you're still using the material UI, tell me if there's any issues with v88.

**Comment by HenryB96** [comment]
Unfortunately it still doesn't appear to be working. The videos don't seem to be changed at all by the update.

**Comment by Zren** [comment]
Uhg. Can you provide a screenshot of what Youtube looks like? What browser?

Can you also tell me what your `VISITOR_INFO1_LIVE` cookie is (this is what determines which version of youtube you're using/testing)?

On chrome, hit F12, then go to the "Application" tab, the under "Cookies" in the sidebar, select youtube.com.

![](https://i.imgur.com/fozUINJ.png)

**Comment by Zren** [comment]
Also are you using any other Youtube userscripts?

**Comment by HenryB96** [comment]
Sure, here's what YouTube looks like:
<img width="1440" alt="screen shot 2016-10-26 at 12 44 51" src="https://cloud.githubusercontent.com/assets/8763569/19735591/40010872-9b7a-11e6-8e32-53407f2ea2c7.png">

And the cookie:
<img width="483" alt="screen shot 2016-10-26 at 12 45 48" src="https://cloud.githubusercontent.com/assets/8763569/19735598/478f7394-9b7a-11e6-87fb-eb00996fffe5.png">

I'm not using any other YouTube userscripts. I do use Magic Actions for YouTube, but disabling that doesn't make a difference with regards to videos being resized.

**Comment by Zren** [comment]
Does turning off my script show the same look? Do you have any other extensions or CSS? Does it look the same in incognito/private browsing mode?

**Comment by HenryB96** [comment]
Turning the script off shows the same look. In incognito mode with all other extensions disabled and the script on (with TamperMonkey allowed to run in incognito), it looks the same as normal browsing mode with the other extensions on.

Is there any debugging information I can give you through the Chrome console or anything like that that'll help?

**Comment by Zren** [comment]
Oh nevermind, I forgot that layout with black borders on the left/right is cinema/wide mode, not an extension. >.<'

Open the Console, check the "hide network errors" checkbox if you have an adblocker, and refresh the page.

![](https://i.imgur.com/hDQlLAi.png)

**Comment by HenryB96** [comment]
Sure, here you go:
<img width="555" alt="screen shot 2016-10-26 at 18 21 30" src="https://cloud.githubusercontent.com/assets/8763569/19747332/0efb172a-9ba9-11e6-9583-b34d0149abea.png">

**Comment by Zren** [comment]
Okay, so it's not loaded at all? What browser / extension are you using? Have you tried reinstalling the script from greasyfork?

**Comment by HenryB96** [comment]
I'm using Chrome 54.0.2840.71 (64-bit, Mac) with TamperMonkey to load the script. I've tried reinstalling a couple of times.

I'm literally only using TamperMonkey for your script so if you have a recommended alternative I can try with that?

**Comment by HenryB96** [comment]
Oh hang on - I just reinstalled TamperMonkey and it seems to be working fine now. I guess there was something wonky with my TM installation that broke scripts. 

Thanks for your help!

**Comment by Zren** [comment]
Glad we got it working!
