### ISSUE TITLE
Version 92 + Firefox 52.0.2: script eats a TON of CPU when videos change in a playlist

### ISSUE THREAD

**Issue by JarrettBillingsley** [Zren/ResizeYoutubePlayerToWindowSize#25]
If I'm playing a playlist, whenever the next video loads, the script uses a ton of CPU, lagging the entire browser for sometimes 10-20 seconds. Firefox will sometimes pop up the "stop script" dialog. 

Reloading the page after the video has changed does not exhibit the behavior.

Please let me know if you need more details/debug output/whatever!

**Comment by Zren** [comment]
Oh wow, thanks for pointing that out. Chrome doesn't have that warning, and I never noticed it.

Looks like `yt.pubsub2` no longer exists, so it kept binding the listeners for `yt.pubsub` (the first version) every second, causing a crazy amount of initialisation calls when the video changed.

Just uploaded v94 with the fix.

**Comment by JarrettBillingsley** [comment]
Wow, fantastic response time, thanks :D
