### ISSUE TITLE
Doesn't work properly with the new design update. Material UI

### ISSUE THREAD

**Issue by ChildishGiant** [Zren/ResizeYoutubePlayerToWindowSize#26]
If you go from a video, onto a channel it breaks.

**Comment by Zren** [comment]
"Breaks" how? What web browser? Are you using the old UI or the new Material UI?

**Comment by Zren** [comment]
What version are you using?

**Comment by SolarPolarMan** [comment]
For some reason it's still on 92 even though the update url works. I'll update then check if it's fixed.

**Comment by SolarPolarMan** [comment]
Updated and this still seems to be an issue. [Here's a recording](https://youtu.be/LfMa-EOK41k).

**Comment by SolarPolarMan** [comment]
Same happens going from a video to a search.

**Comment by Zren** [comment]
Yeah,  the material ui changed a few event listeners around and its not detecting when the new page loads. I tried looking for a javascript event last night but that doesnt exist. I think ill have to check the url every second and fire then.

**Comment by SolarPolarMan** [comment]
:( can't you `$(document).load(function() {})` or some form of on load? I have no knowledge of the youtube backend btw

**Comment by Zren** [comment]
Heh, if only it was that easy. Every time you see the red line at the top of the page, it's downloading that page and replacing parts of the page instead of doing a full page reload. It makes it faster, but much harder to hook into.

**Comment by SolarPolarMan** [comment]
So unless they purposefully add an event, you'll have to bodge it?

**Comment by Zren** [comment]
I either have to monkey patch one of the functions (replace
window.history.pushState with my own function then call the old function),
which I tried last night, but couldn't get it working. So I'll write a hack
tonight just to get it working until I find a better way.

**Comment by Zren** [comment]
Tell me if v95 has any problems.

**Comment by SolarPolarMan** [comment]
Seems to be fixed. Will reopen if this comes up again 😄 Thanks for the hotfix!

**Comment by Aidoboy** [comment]
It seems to be broken again, at least for me.

**Comment by SolarPolarMan** [comment]
I've also seen it not working but I haven't been able to replicate it.

**Comment by SolarPolarMan** [comment]
Ah the from video to channel bug is back.

**Comment by Aidoboy** [comment]
Yeah, same.

**Comment by Zren** [comment]
Bleh, screw this, they've removed the function I was using to subscribe to events. I'll just check stuff if the player has loaded periodically using a timer.

Tell me if there's any problems with v96.
