### ISSUE TITLE
Half bar :(

### ISSUE THREAD

**Issue by riccardosimo** [Zren/ResizeYoutubePlayerToWindowSize#28]
Hi... i'm using firefox 54.0 and even after i updated the script to 102 the issue is still here... 😢 
![cattura](https://user-images.githubusercontent.com/8348630/27382050-8db6bcc6-5685-11e7-85dc-8363d8bb218e.jpg)

**Comment by Aidoboy** [comment]
Click the button right next to the fullscreen button

**Comment by riccardosimo** [comment]
@Aidoboy ok but it's just a temporary fix 😭

**Comment by riccardosimo** [comment]
Half bar is back :(

**Comment by Zren** [comment]
All the time, or sometimes?

**Comment by Aidoboy** [comment]
When I'm in Chrome, it almost always happens, but in Nativefier it almost
never happens.

**Comment by Zren** [comment]
Looks like the script is trying to hit the "theater mode" button too early. I'll try adding some code that will constantly try to press it until the mode changes.
