### ISSUE TITLE
Doesn't seem to work on livestreams with the "/c/<user>/live" URL

### ISSUE THREAD

**Issue by JarrettBillingsley** [Zren/ResizeYoutubePlayerToWindowSize#29]
Both Chrome and FF. The `watch?v=<id>` URLs work fine.

https://www.youtube.com/c/Kitten%20Academy/live

**Comment by Zren** [comment]
How are you linked to those pages?

* This works for me `/channel/<channel_id>/live`  
  https://www.youtube.com/channel/UCSJ4gkVC6NrvII8umztf0Ow/live
* This 404s though `/c/<channel_id>/live`  
  https://www.youtube.com/c/UCSJ4gkVC6NrvII8umztf0Ow/live

**Comment by JarrettBillingsley** [comment]
I think we had a race condition, I edited the issue and added an example link.

**Comment by Zren** [comment]
Ah, it only supports `/c/<channel_name>/live` but it doesn't explain what page links to these pages.

https://www.youtube.com/channel/UC83RKJs4eKHVE9v0YUyqzgg links to https://www.youtube.com/watch?v=0U2yPSC8Sow and https://www.youtube.com/watch?v=FFwbII94meY (there's 2 live streams).
Clicking on the "Kitten Academy" header link directs me to https://www.youtube.com/user/scribblej but the links still use `watch?v=`.

**Comment by JarrettBillingsley** [comment]
Someone I follow often tweets links to her livestream in that `/c/<channel_name>/live` format. I'm not sure where she gets that link though.

**Comment by Zren** [comment]
Ah k. Was just wondering why I'd not seen it before. It's a really easy fix to do. I just need to update `ytwp.util.isWatchUrl`.

**Comment by Zren** [comment]
v106 should fix things

**Comment by BubiBalboa** [comment]
I don't know if it was fixed and is broken again or what but `youtube.com/user/<channel_name>/live` does not work with the current version 122 with Firefox 68b and Violentmonkey.

**Comment by Zren** [comment]
I didn't know about https://www.youtube.com/user/pokemon/live paths.

Look for `ytwp.isWatchUrl`, we need to change the regex from `\/(c|channel)\/[^\/]+\/live` to `\/(c|channel|user)\/[^\/]+\/live`. I'll put it in v123.

https://github.com/Zren/ResizeYoutubePlayerToWindowSize/blob/master/153699.user.js#L202

**Comment by BubiBalboa** [comment]
It works! That's was an easier fix than I thought it would be. Thanks!
