### ISSUE TITLE
Conflicts with Iridium's player always visible feature

### ISSUE THREAD

**Issue by Keith94** [Zren/ResizeYoutubePlayerToWindowSize#30]
https://github.com/ParticleCore/Iridium/wiki/Features#player_always_visible

With the above setting enabled in [Iridium](https://github.com/ParticleCore/Iridium), the player doesn't resize when scrolling down the page, so it blocks all other page content. So without having to disable that setting in Iridium, is there any other way to make both the scripts work together properly?

**Comment by Zren** [comment]
Wow, js crypto mining is really gonna be a thing... >.>

Anyways, v110 fixes it.
