### ISSUE TITLE
Hide scroll bar on Firefox

### ISSUE THREAD

**Issue by Keith94** [Zren/ResizeYoutubePlayerToWindowSize#31]
The scroll bars on video pages kinda detracts from the 'fullscreen' video appearance; is there any way to hide those for only the video pages? I tried css `overflow-y:hidden;` but that breaks scrolling completely.

**Comment by Zren** [comment]
You'll have to use another extension for that. Firefox v56 and below required an "agent stylesheet" when I used to use Stylish. No idea if it works for v57.

**Comment by Keith94** [comment]
I couldn't really find any solutions, besides [this](https://greasyfork.org/en/scripts/33562-firefox-57-autohide-scrollbars/code). Thanks anyway. If you have suggestions let me know.
