### ISSUE TITLE
Please update for the new firefox system (version 57)

### ISSUE THREAD

**Issue by riccardosimo** [Zren/ResizeYoutubePlayerToWindowSize#32]
With the new firefox addons system the script doesn't works anymore :(

**Comment by Zren** [comment]
Did it revert to the youtube layout before Material Design? I've readded compatibility with the old layout.

I've also made it attempt to enter theater mode every second in v111 (rather than just 10 attempts over the first 2 seconds on load).

**Comment by JarrettBillingsley** [comment]
For me, in 57, it full-sizes the video but the YouTube search bar is at the top overlaying the video.
