### ISSUE TITLE
ICO to SVG

### ISSUE THREAD

**Issue by krystian3w** [Zren/ResizeYoutubePlayerToWindowSize#34]
Maybe change icon from ico to svg:

```
https://www.youtube.com/yt/about/media/images/brand-resources/icons/YouTube_icon_full-color.svg
```

or bigger png:

```
https://s.ytimg.com/yts/img/favicon_96-vflW9Ec0w.png
```

> ![youtube](https://s.ytimg.com/yts/img/favicon_96-vflW9Ec0w.png) |
>  --- |

**Comment by Zren** [comment]
Do we need anything larger than a [32x32 png](https://s.ytimg.com/yts/img/favicon_32-vflOogEID.png)? I mostly use the ico in my scripts since it's an internet standard so I don't have to skim the `<head>` for the icon url.

**Comment by krystian3w** [comment]
> Do we need anything larger than a 32x32 png?

 I think no, tihis size look better in Violentmonkey than 16x16 ico.
