### ISSUE TITLE
Doesn't work anymore with violentmonkey

### ISSUE THREAD

**Issue by riccardosimo** [Zren/ResizeYoutubePlayerToWindowSize#35]
The script is not working anymore with Firefox version 60.0 :( but still works with chrome.. can you please update the script? :)

**Comment by Zren** [comment]
What specifically doesn't work?

![](https://i.imgur.com/4JkcYe8.png)

**Comment by riccardosimo** [comment]
![immagine](https://user-images.githubusercontent.com/8348630/39005121-8dd1ca30-43ff-11e8-9879-b1050d0c2178.png)

I also tried in private windows in firefox but nothing change :( i mainly use firefox but i tried to use the script in chrome just to see if it was a script problem or not and in chrome still works fine... (i have the same version as you in firefox)

**Comment by Akadius** [comment]
The problem is with the new version of violentmonkey, not firefox. Change to tampermonkey of greasemonkey and it'll work just fine. Also, just install an adblock instead of using this "auto close yt ads" script.

**Comment by Akadius** [comment]
The problem is with the new version of violentmonkey, not firefox. Change to tampermonkey or greasemonkey and it'll work just fine. Also, just install an adblock instead of using this "auto close yt ads" script.

**Comment by riccardosimo** [comment]
😮 with tampermonkey it works :\ can i ask you why it doesn't works with violentmonkey?

**Comment by krystian3w** [comment]
Update violentmonkey to 2.9.3 https://github.com/violentmonkey/violentmonkey/issues/400

**Comment by riccardosimo** [comment]
Love you guys. I hope you'll never leave this awesome script :D thank you again :)
