### ISSUE TITLE
Recently started acting weird (just.. read this lol)

### ISSUE THREAD

**Issue by JarrettBillingsley** [Zren/ResizeYoutubePlayerToWindowSize#39]
The YouTube bar is now overlaying the video; the video overlays the info/comment section; and there's a large blank space above the video that can be scrolled into.

**Comment by Zren** [comment]
What does your `VISITOR_INFO1_LIVE` look like? Right click the page (not the player), then click "Inspect". Click the "Application" tab, then expand "Cookies" and select "https://www.youtube.com".

![](https://i.imgur.com/m2dKpBr.png)

Don't take a screenshot of it, as another cookie is used for being "logged in" as you.

**Comment by JarrettBillingsley** [comment]
Wait -- how am I supposed to explain what it looks like without taking a screenshot? 😅 

I mean, it looks similar to that, but with a different string of characters. Do you need that? lol

**Comment by Zren** [comment]
Yep, just copy and paste the string of characters (it's case sensitive). You can double click the text to select it.

**Comment by JarrettBillingsley** [comment]
L59pzm2ymqw

**Comment by Zren** [comment]
Yeah sorry, I don't think that seems to work for "switching" between youtube versions anymore. You'll have to wait till I see that version of youtube for it to get fixed.

Do you have any other youtube extensions scripts enabled?

**Comment by JarrettBillingsley** [comment]
Nope. I'm on Firefox, for what it's worth.

**Comment by JarrettBillingsley** [comment]
I got an extension for FF that "restores the old firefox layout" (??) and besides making YT load so much faster and be far more responsive, it also fixes the issues above. So uh, hm. There's another data point I guess?

**Comment by Zren** [comment]
Old versions will definitely work. It's the newer versions of Youtube that are still under A/B testing that I have not seen yet that tend to break my script.

What extension are you using btw?

**Comment by JarrettBillingsley** [comment]
YouTube Classic 1.2. https://github.com/thisdotvoid/youtube-classic-extension

**Comment by draggy** [comment]
Just wanted to say that I have this same issue. It only started a few days ago. Chrome 68.0.3440.75, VISITOR_INFO1_LIVE 7ii89Ji7VuQ
