### ISSUE TITLE
Scrollbar in Firefox

### ISSUE THREAD

**Issue by MrFr1day** [Zren/ResizeYoutubePlayerToWindowSize#42]
Hi,

First, thank you for sharing this great script.

Unlike Chrome, the scrollbars in Firefox are not hidden, is this by design? or a Firefox issue?
There is an old addon/script (YouTube Center) that had the same feature and handled the scrollbar better, it made the scrollbar visible only when you scroll down.

Unrelated question, I've seen code in your script that handles the Guide sidebar (at least that what I think it is), and I was wondering if it possible to make the Guide sidebar collapsed by default everywhere?

Thanks.

**Comment by Zren** [comment]
> a Firefox issue?

Yes, scrollbar's cannot be "styled" in firefox without an extension.

https://stackoverflow.com/questions/6165472/custom-css-scrollbar-for-firefox

Youtube Center gets around this by "switching modes". You scroll up to the top of the page, then scroll up two clicks and it will hide the normal page with the scrollbar and display just the video.

There's probably a Firefox extension that hides the scrollbar, but it probably applies to every website and not just youtube video pages.

> Unrelated question, I've seen code in your script that handles the Guide sidebar (at least that what I think it is), and I was wondering if it possible to make the Guide sidebar collapsed by default everywhere?

It seems you need to remove the `opened` attribute from `<app-drawer id="guide">`

It's too much work for me to figure out how to make sure the guide is closed only when the page loads and not close it when you manually open it sorry.

```
        var appDrawer = document.querySelector('app-drawer#guide')
        if (appDrawer) {
            appDrawer.removeAttribute('opened')
        }
```

**Comment by Zren** [comment]
The `scrollbar-width: none` CSS property hidden behind a `about:config` flag in FireFox v63 looks promising.

https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width

1. Go to `about:config`,  `layout.css.scrollbar-width.enabled: true`
2. Restart Firefox

I still need to add some CSS to the userscript though. Something like `scrollbar-width: none;`.

**Comment by krystian3w** [comment]
Possible detect 1 screen scrolled down?

**Comment by MrFr1day** [comment]
Hi,

I made a script that show/hide the scrollbar based on a scroll threshold (it also stops text selection when pressing on the video, which I noticed it happens a lot when using your script), maybe you should consider adding similar functions.

Here is the script if anyone is interested:

    var scrollbarVisible = 0;
    var scrollThreshold = 400;
    var sheet = (function() {
        var style = document.createElement("style");
        document.head.appendChild(style);
        return style.sheet;
    })();

    window.addEventListener('scroll', toggleScrollbar, false);
    document.getElementById("movie_player").onselectstart = function() {return false};

    function toggleScrollbar() {
      if (window.scrollY < scrollThreshold && scrollbarVisible) {
        scrollbarVisible = 0;
        sheet.deleteRule(0); 
      } else if (window.scrollY > scrollThreshold && !scrollbarVisible) {
        scrollbarVisible = 1;
        sheet.insertRule("html { scrollbar-width: auto !important; }", 0);    
      }  
    };

**Comment by Zren** [comment]
Firefox v64 has `scrollbar-width` enabled by default, and v120 of this script added the CSS, so closing this.

https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width#Browser_compatibility

Not personally interested in having the page contents resize to show the scrollbar after a threshold. A user needs to be able to scroll without it to even use this script anywho.
