### ISSUE TITLE
Fullscreen breaks the page making it white

### ISSUE THREAD

**Issue by TagoDR** [Zren/ResizeYoutubePlayerToWindowSize#43]
Hello
Yesterday I noticed that when I try to watch YouTube videos full screen it all becomes white and the controls are not accessible, using the ESC key I was able to exit it but the page itself has become white. The audio was going on the background all the while. 
On the console log I notice its reaches max attempt “ytwp.attemptToUpdatePlayerTick 150“
YouTube might have broken something.
I look around in my pc for possible conflicts like extensions, scripts, browser, graphics card driver, but I could not find anything.
If I disable your script fullscreen works fine. I peeked at your code but I could not find anything conclusive, I'm not used to youtube code so its very confusing to me, I wish you luck finding the cause.

**Comment by Zren** [comment]
Which browser?

I just tried loading a video in Firefox (after navigating from the homepage), I got a black screen (I'm in dark mode) when the page loaded. This might be unrelated as you mentioned "full screen".

![2018-11-15___17-09-33](https://user-images.githubusercontent.com/416367/48585081-87581e80-e8f9-11e8-8ee1-4507869f21cd.png)

It looks like it might be trying to switch to theater mode too soon.

Does this bug happen even with a page refresh (F5)? Youtube seems to work fine if I open Youtube in a 2nd tab.

Holy shit, Youtube implemented my script's concept into their fullscreen mode!

![2018-11-15___17-16-14](https://user-images.githubusercontent.com/416367/48585296-34329b80-e8fa-11e8-8343-a2d5c72b0622.png)

![2018-11-15___17-17-58](https://user-images.githubusercontent.com/416367/48585375-71972900-e8fa-11e8-802a-56b58b646bca.png)

**Comment by Zren** [comment]
* `<ytd-app>`
    * Theater: `style="--yt-swatch-primary:rgb(35,35,35); --yt-swatch-primary-darker:rgb(32,32,32); --yt-swatch-text:rgb(255,255,255); --yt-swatch-important-text:rgb(255,255,255); --yt-swatch-input-text:rgba(255,255,255,1); --yt-swatch-textbox-bg:rgba(19,19,19,1); --yt-swatch-logo-override:rgb(255,255,255); --yt-swatch-icon-color:rgba(136,136,136,1); --ytd-masthead-height:56px;"`
    * FullScreen: `style="--yt-swatch-primary:rgb(35,35,35); --yt-swatch-primary-darker:rgb(32,32,32); --yt-swatch-text:rgb(255,255,255); --yt-swatch-important-text:rgb(255,255,255); --yt-swatch-input-text:rgba(255,255,255,1); --yt-swatch-textbox-bg:rgba(19,19,19,1); --yt-swatch-logo-override:rgb(255,255,255); --yt-swatch-icon-color:rgba(136,136,136,1); --ytd-masthead-height:0px;"`

So it changed `--ytd-masthead-height:56px;` to `0px` using javascript.

* `id="movie_player"`
    * Normal: `class="html5-video-player ytp-transparent ytp-large-width-mode ad-created playing-mode iv-module-loaded ytp-hide-info-bar ytp-autohide"`
    * Theater: `class="html5-video-player ytp-transparent ytp-large-width-mode ad-created playing-mode iv-module-loaded ytp-hide-info-bar ytp-autohide"`
    * FullScreen: `class="html5-video-player ytp-transparent ytp-large-width-mode ad-created playing-mode iv-module-loaded ytp-fullscreen ytp-big-mode ytp-autohide"`

So it added: `ytp-fullscreen ytp-big-mode`

Hmmm. Looks like it might not be a simple toggle to enter this mode with a css class or tag attribute. Ah well. I'll look again after supper.

**Comment by TagoDR** [comment]
I happens in Waterfox and Firefox, for me it only triggers/crash to white if I try to fullscreen it, else it works fine.

**Comment by krystian3w** [comment]
I have same bug.

**Comment by Zren** [comment]
I just experience this bug today. A fix will be uploaded soon, just gotta test a little more.

**Comment by Zren** [comment]
v122 should fix this bug.

**Comment by krystian3w** [comment]
OK, thank you.
