### ISSUE TITLE
FullScreen tribe broken after YouTube added new option "Scroll for details"

### ISSUE THREAD

**Issue by krystian3w** [Zren/ResizeYoutubePlayerToWindowSize#45]
![obraz](https://user-images.githubusercontent.com/35370833/51216573-2498f880-1925-11e9-9e31-e014d66408e4.png) |
--- |

Now in fullscreen possible see comments / description / up next.

**Comment by Zren** [comment]
What specifically is broken in the new version of YouTube? This sort of sounds like #43, but I still can't reproduce that bug.

I know scroll for details exists when in fullscreen, but the point of this script is to avoid going fullscreen. My version of youtube has the "scroll for details" feature in fullscreen, and it's working in both Chromium and Firefox without any issues that I've noticed.

**Comment by BubiBalboa** [comment]
I have the same issue and it is almost the same like the problem the script has had in the past. Only difference is you don't have to reload the page to get the video to play after exiting fullscreen mode. 

You enter fullscreen, the video keeps playing I the background and the screen turns dark grey. Switching the script off fixes the problem.

I hope this description helps.

**Comment by krystian3w** [comment]
> Switching the script off fixes the problem.

Nope, navigation when moved to high with `CleanTube For YouTube` 

https://userstyles.org/styles/157126/cleantube-for-youtube-2018

![obraz](https://user-images.githubusercontent.com/35370833/51426814-50033800-1bf0-11e9-8a1f-98aa850fbdad.png)


But this is propably bug in CSS `CleanTube For YouTube`.

**Comment by BubiBalboa** [comment]
Yeah, I don't use clean tube so I wouldn't know. I only have the described fullscreen problem.

**Comment by krystian3w** [comment]
I try find bug in `CleanTube` if still broke with `v122`.
