### ISSUE TITLE
Script pushes list of live broadcasts where it should do nothing

### ISSUE THREAD

**Issue by mirmalis** [Zren/ResizeYoutubePlayerToWindowSize#46]
Script pushes list of live broadcasts where it should do nothing, on games 'Live' tab (such as https://www.youtube.com/channel/UC1ERAqx0EIMpr_uA4BD2WUw/live). 
This would help:
```
// @exclude         http*://*.youtube.com/channel/*/live
// @exclude         http*://youtube.com/channel/*/live
// @exclude         http*://*.youtu.be/channel/*/live
// @exclude         http*://youtu.be/channel/*/live
```

**Comment by Zren** [comment]
It's not that easy. This is a feature added in Issue #29. These urls are valid video pages:

* https://www.youtube.com/user/pokemon/live
* https://www.youtube.com/channel/UCFctpiB_Hnlk3ejWfHqSm6Q/live
* https://www.youtube.com/c/Kitten%20Academy/live

It looks like I need to check if it's still a "watch" [video] page as well after the page loads for these "auto-generated" gaming channels.

**Comment by Zren** [comment]
Tell me if you have any issues with:

```
    ytwp.isWatchUrl = function (url) {
        if (!url)
            url = uw.location.href;
        if (url.match(/https?:\/\/(www\.)?youtube.com\/(c|channel|user)\/[^\/]+\/live/)) {
            if (document.querySelector('ytd-browse')) {
                return false
            } else {
                return true
            }
        }
        return url.match(/https?:\/\/(www\.)?youtube.com\/watch\?/);
    };
```

I've no idea where to click a `/channel/asdfsdf_aswdfsadf/live` link on YouTube, so I can't test YouTube's "dynamic page loading".

**Comment by mirmalis** [comment]
This fix seems to work for me.
You can find autogenerated gaming channels here: [https://www.youtube.com/gaming/games](https://www.youtube.com/gaming/games)

**Comment by Zren** [comment]
Ah, your autogenerated `/live` links are easy to find (just gotta visit the "home" of a channel). I can't find a live links from #29 on YouTube itself anywhere. I think it's a url used for sharing on twitter or something.
