### ISSUE TITLE
control buttons jumping around?

### ISSUE THREAD

**Issue by ksdixon** [Zren/ResizeYoutubePlayerToWindowSize#47]
Is this just me?

The control buttons jump around from the middle to stretching across the width of the resized-to-window youtube video. It makes it espeically hard to, say, change the stream quality, as it closes the control button menus when it jumps around.

**Comment by Zren** [comment]
Works fine for me in Firefox, even logged out in Incognito/Private mode. Chromium works fine too.

The script will auto select YouTube's "theater" mode every second, since it properly scales the video player GUI while the "normal" mode does not.

I assume a new version of YouTube (that only you can see at the moment) is causing the bug.

**Comment by ksdixon** [comment]
I've been dealing with it for years, not sure why I never put a comment before now.

Ahh, theatre view mode, that probably explains why the controls were jumping from the right-side into the middle of the bar. I'll make sure that the YT video player is set to cinema mode, and hopefully the problem will go away. I'll report back if the problems return.

**Comment by ksdixon** [comment]
Ah.. I've reproduced it. It's to do with zooming-in the youtube page (to make the control buttons bigger with my crappy eyesight).

Zooming into, say 150%, makes the control button bar jump from middle-right. Is there anything you can do to fix this for me?

**Comment by ksdixon** [comment]
edit: zooming-in when snapped to half-screen (windows 10).
sorry, I couldn't edit my last message.

**Comment by Zren** [comment]
I can't reproduce it, even with a 200% zoom on my 1080p monitor. I regularly resize YouTube to use a smaller window than the available room for the number of buttons in the bottom right of the player, but when there isn't enough room, it just hides the fullscren, settings, miniplayer, etc icons.

**Comment by ksdixon** [comment]
I had to do a loot of troubleshooting from scratch on a blank firefox profile, as so many addons were saying non-verified or corrupted. But I think I have nailed-down the offending tweak that interferes...

Background Info
- Install FF55 64bit - still on old FF because I need my addons/userscripts to continue working
- Launch FF, options page turn off automatic updates, close FF again.
- It will have automatically installed FF56, so install/'upgrade' back to FF55.

Addons:
- Zoom Control + custom zoom settings
- Greasemonkey 3.6 & Resize YT to Window script 124

You're right, with FF window snapped to half-screen, and changing from 155%-160% custom zoom, YT removes settings gear icon from taskbar. That's fine, as I'm happy with the button sizes at this custom zoom level.

Here's the problem, the about:config tweak that can produce the issue when applied, and turn off the control jumping-issue when turned off:

youtube - revert to old "watch list" layout
-------------------------------------------------
- about:config
- new string
- general.useragent.override.youtube.com
- Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0

Would you know any way to retain the old WL layout without messing-up the control button taskbar?

**Comment by Zren** [comment]
Oh, are you using the old youtube layout? `&disable_polymer=true`?

Eg: https://www.youtube.com/playlist?list=WL&disable_polymer=true

I was able to reproduce: https://www.youtube.com/watch?v=dDAZxflX6nc

Try one of the older versions of the script? From before the Material/Polymer update?

https://greasyfork.org/en/scripts/811-resize-yt-to-window-size/versions

* v118?
  * https://github.com/Zren/ResizeYoutubePlayerToWindowSize/blob/master/changelog.md#118---may-19-2018
  * https://greasyfork.org/en/scripts/811-resize-yt-to-window-size?version=598556
* v87?
  * https://github.com/Zren/ResizeYoutubePlayerToWindowSize/blob/master/changelog.md#88---october-25-2016
  * https://greasyfork.org/en/scripts/811-resize-yt-to-window-size?version=145563

**Comment by ksdixon** [comment]
OMG! v87 works great along with the about:config tweak to disable polymer, the easiest route for sure. 

I had been trying to get my head round the formula to use with the Redirector FF addon to intercept any playlist formatted youtube url, and add "&disable_polymer=1 " onto the end of the url, but I couldn't figure it out. Now I don't have to, as everything is working.

I now have old Watch List/Playlist layout, and resized YT videos with non-jumping control buttons. Thank you so much, i'd been suffering for years, I totally should have asked sooner!
