### ISSUE TITLE
The video is too high up on Crunchyroll

### ISSUE THREAD

**Issue by Dyras** [Zren/ResizeYoutubePlayerToWindowSize#50]
Greetings! Any chance you could add an option to make the video sit lower when the browser window covers 50% of the screen? Tried both Chrome and Edge Beta and it's always too high up for me.
As it is now, there's a lot of black area at the bottom and none on top. I'd rather have the same size and position as with Improved YouTube.

Two images for demonstration:
https://i.vgy.me/3IYhbq.png
https://i.vgy.me/dEj9EA.png

This seems to be what Crunchyroll is like on the image over at Greasyfork, too!
https://i.imgur.com/bdoXOQc.png

**Comment by Zren** [comment]
The screenshot was from Crunchyroll's flash player which would center the video inside the iframe if I adjusted the iframes height. When I rewrote the crunchyroll code for the new HTML5 player, I couldn't think of a simple solution to vertically center it at the time. Anyways, I also replied (and get email notifications) on greasyfork's forum. This is for another script so closing.
