### ISSUE TITLE
Using as bookmarklet on iPadOS

### ISSUE THREAD

**Issue by LampPrinter** [Zren/ResizeYoutubePlayerToWindowSize#53]
I am using this script as a bookmarklet on iPadOS. Instead of opening YouTube and then running this script every time, I was wondering if both actions can be combined and this script opens YouTube.com as default when no URL is provided.

**Comment by Zren** [comment]
This would change the webpage:
```js
if(window.location.href=='about:home'){document.location.href='https://youtube.com'}
```

However the page change would reset all javascript on the page, and you'd need to press the bookmarklet again.

So no.
