### ISSUE TITLE
The script stopped working since today :(

### ISSUE THREAD

**Issue by riccardosimo** [Zren/ResizeYoutubePlayerToWindowSize#55]
I'm using Microsoft Edge and the script stopped working today :( it doesn't resize the videos :(

**Comment by Zren** [comment]
Did the website change? Does it still move the video up to the top? Does the black area fill the screen? Is it just the controls that do not resize? Or is it the video too?

Screenshot?

**Comment by riccardosimo** [comment]
It's like the script doesn't exist 🤷‍♂️ 
![image](https://user-images.githubusercontent.com/8348630/93666866-c28d8080-fa81-11ea-9018-3fd4b2d303fe.png)


> Did the website change? Does it still move the video up to the top? Does the black area fill the screen? Is it just the controls that do not resize? Or is it the video too?
> 
> Screenshot?

**Comment by Zren** [comment]
Can you hit F12 to open [Edge's Developer Tools](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide). Go to the console and see if there's any `[ytwp]` logs? You may need to refresh the page with the inspector open.

**Comment by riccardosimo** [comment]
> Can you hit F12 to open [Edge's Developer Tools](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide). Go to the console and see if there's any `[ytwp]` logs? You may need to refresh the page with the inspector open.

![image](https://user-images.githubusercontent.com/8348630/93710336-1d88ab80-fb46-11ea-80d7-dc4d7e81970b.png)

**Comment by Zren** [comment]
That's not a screenshot of the Console. You're displaying the "Element" tab up top. And below you're showing the "Novita" (What is new) tab.

**Comment by riccardosimo** [comment]
> That's not a screenshot of the Console. You're displaying the "Element" tab up top. And below you're showing the "Novita" (What is new) tab.

Yeah sorry 😂🤦‍♂️
![image](https://user-images.githubusercontent.com/8348630/93718793-9c99d600-fb7e-11ea-840e-5a1dc4b458b5.png)

**Comment by Zren** [comment]
So there's 0 `[ytwp]` logs?

**Comment by riccardosimo** [comment]
> So there's 0 `[ytwp]` logs in the console?

No 🤔

**Comment by Zren** [comment]
Could you take a screenshot of the last few `[ytwp]` and any errors (red messages) that appear after the last `[ytwp]` message.

**Comment by riccardosimo** [comment]
> Could you take a screenshot of the last few `[ytwp]` and any errors (red messages) that appear after the last `[ytwp]` message.

I made a video
[https://streamable.com/frzace](url)

**Comment by Zren** [comment]
Doesn't look like the script is running at all. Did you try refreshing the page after opening the console? Are you on a video page when you refresh?

This is the sort of stuff you should be seeing:

![2020-09-21___10-04-44](https://user-images.githubusercontent.com/416367/93776961-2cc53300-fbf2-11ea-8998-4bc2fd197df5.png)

How are you loading the userscript in Microsoft Edge? Tampermonkey? Or is script support native to Edge?

**Comment by riccardosimo** [comment]
> Doesn't look like the script is running at all. Did you try refreshing the page after opening the console? Are you on a video page when you refresh?
> 
> This is the sort of stuff you should be seeing:
> 
> ![2020-09-21___10-04-44](https://user-images.githubusercontent.com/416367/93776961-2cc53300-fbf2-11ea-8998-4bc2fd197df5.png)
> 
> How are you loading the userscript in Microsoft Edge? Tampermonkey? Or is script support native to Edge?
I use Violentmonkey to manage the scripts
https://streamable.com/n8e356

**Comment by Zren** [comment]
Could you try copying the script (`Ctrl+C`), then pasting it in the console (`Ctrl+V`)? Then hit `Enter` to run the JavaScript.

https://www.youtube.com/watch?v=_8ZzCWKDcOQ

I also noticed YTLyrics in the console, and "Enhancer for Youtube" classes in the Elements view.

If running the script in the console doesn't work normally, could you also try in a private/incognito window? Assuming those extensions don't activate in private windows.

**Comment by riccardosimo** [comment]
> Could you try copying the script (`Ctrl+C`), then pasting it in the console (`Ctrl+V`)? Then hit `Enter` to run the JavaScript.
> 
> https://www.youtube.com/watch?v=_8ZzCWKDcOQ
> 
> I also noticed YTLyrics in the console, and "Enhancer for Youtube" classes in the Elements view.
> 
> If running the script in the console doesn't work normally, could you also try in a private/incognito window? Assuming those extensions don't activate in private windows.

Yeah pasting it in the console works 😮 so what? What could be the problem? I actually installed Enhancer for youtube until i fix this problem with the script (obviously i disable it when i try to run the script)

**Comment by riccardosimo** [comment]
Ok edge has been updated and now everything works again :) thank you <3
