### ISSUE TITLE
Translucent Overlay  On Mouse Hover

### ISSUE THREAD

**Issue by darksky82** [Zren/ResizeYoutubePlayerToWindowSize#61]
There is an ugly translucent layer that covers the entire player when mouse hovers on the player area. Can this be removed by any chance? The problem is, since the player covers the entire fold of the screen, the mouse pointer is always on the player when the page loads, thus rendering this translucent layer on the player, causing pain. 
ps. the translucent area is caused by the seek bar and player controls appearing when you hover over the window.

**Comment by Zren** [comment]
The player controls overlay hides if you hover the middle of the video while it's playing. Don't hover the controls or it'll keep them visible.
