### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by TehDarkAbyss** [Zren/ResizeYoutubePlayerToWindowSize#62]
Firefox 85.0.1
Greasemonkey 4.11
Resize YT To Window Size 124

No other add-ons or userscripts.

I think Youtube changed something and that's what broke this. I tried other options to chance the video player size and those were also not working.

**Comment by Zren** [comment]
Seems to work for me in Firefox v85 and Chromium v88 in Linux. I'm guessing I'm not in a whatever Youtube A/B test you are in though.

**Comment by TehDarkAbyss** [comment]
Didn't change anything and it started working again with ver 124. Updated too ver 125 and also still working. Don't know what happened.
