### ISSUE TITLE
Option to only enable script by key toggle

### ISSUE THREAD

**Issue by Bartek200219** [Zren/ResizeYoutubePlayerToWindowSize#67]
Option to disable automatic resize on load of page, and make it work only with key toggle

**Comment by Zren** [comment]
In `ytwp.materialPageTransition = function() {` and `onWatchInit: function() {`  delete/comment out `ytwp.event.addBodyClass();`. It should be able to toggle with `w`.

**Comment by Bartek200219** [comment]
Thank you!

**Comment by Zren** [comment]
In v130, I've added a simple `enableOnLoad = true` to the top of the script you can change to `enableOnLoad = false`.
