### ISSUE TITLE
可以關自動放大嗎

### ISSUE THREAD

**Issue by leadra** [Zren/ResizeYoutubePlayerToWindowSize#69]
滑鼠點[預設檢視模式]不能變回來，只有w鍵才能縮小，所以希望不要自動放大填充窗口~在哪裡程式碼可以修改auto嗎?
我可以如何修改快捷鍵w為ESC呢?
不好意思麻煩您

auto [ToWindowSize] ,how to false .
[Default View Mode]could't work
'w' can I add 'ESC' keyword?

**Comment by Zren** [comment]
Duplicate of Issue #67

**Comment by Zren** [comment]
In v130, I've added a simple `enableOnLoad = true` to the top of the script you can change to `enableOnLoad = false`.

**Comment by leadra** [comment]
非常感謝你~我爬文不夠詳細
