### ISSUE TITLE
Ultrawide full window zooms in videos instead of black bars

### ISSUE THREAD

**Issue by ToiletUncle** [Zren/ResizeYoutubePlayerToWindowSize#70]
Most YT videos are 16:9 so when resized to full window in my 21:9 ultrawide screen there should be black bars at the sides, keeping the aspect ratio. Something broke recently, now resized videos fill up the width of 16:9 videos to my 21:9 screen, black bars gone, causing videos to be zoomed in.

**Comment by Zren** [comment]
Can't seem to reproduce on Firefox in Linux. I'll try Chrome in Linux next.

Can you reproduce the bug when logged out in Incognito/Private mode in your browser? It might be an A/B test by YouTube.

**Comment by ToiletUncle** [comment]
The problem started again in chrome, even in incognito. Nothing I can be done on my end to resolve this issue.

**Comment by ohohohoo** [comment]
I'd like to chime in. I never had issue like this until today. Maybe Youtube made changes that's being deployed gradually? I'm not sure.

This is what it look like https://i.imgur.com/Yjlym5k.jpeg but basically any videos will be played zoomed like that without the black bar on the side like it used to be before. Restarting as mentioned above has no effect and the only way to see the video normally is by disabling the userscript.

**Comment by hoover900** [comment]
Having the same issue with Firefox on mac OS

**Comment by riccardosimo** [comment]
Same hereeee :(

**Comment by marcelbrode** [comment]
Having the Problem on Chrome on Win 10 and Ubuntu 20.04 as well

**Comment by Zren** [comment]
Yeah I can test it now too. Looks like the new YouTube CSS has:

```
.ytp-fit-cover-video .html5-main-video {
  object-fit: cover;
}
```

Which crops the video. We want

```
.ytp-fit-cover-video .html5-main-video {
  object-fit: contain;
}
```

**Comment by Zren** [comment]
v130 should fix the cropping (and the non-autoplay splash thumbnail).

**Comment by riccardosimo** [comment]
> v130 should fix the cropping (and the non-autoplay splash thumbnail).

Yeeee it works again :D btw I was wondering if it's possible to remove the black bars in the videos 🤔

**Comment by Zren** [comment]
> possible to remove the black bars `in` [around]` the videos

While it would be possible to query the video height. I'd basically need to test 3:2, 16:9, 21:9 videos (and 9:16, 9:21 for vertical phone videos) every time YouTube breaks. Not really interested in a feature that shows like 200px of the YT top nav and maybe the video title.

Just use YT's default theater mode if you don't want to use the full window height.

Or set `playerHeight = '100vh';` to `playerHeight = '90vh';` or something.
