### ISSUE TITLE
Rebind script toggle key w to something else?

### ISSUE THREAD

**Issue by Zren** [Zren/ResizeYoutubePlayerToWindowSize#71]
Hmm, I just noticed that `w` appears to change the caption display style. The rectangle box around text goes from 0% 50% 90% 100% opacity.

**Comment by leadra** [comment]
不好意思~我不知道是不是我關鍵字問題
google代碼~都沒看到哪個正確
Escape不行
ESC不行

**Comment by Zren** [comment]
```
keyup { key: "4", keyCode: 52 }
keyup { key: "ArrowUp", keyCode: 38 }
keyup { key: "Escape", keyCode: 27 }
```

```js
scriptToggleKey = 'Escape'
```

Hmmm, that does not work. Looks like you also need to change from the `keypress` event to the `keyup` event. At the bottom of the script, change 

```js
    scriptToggleKey = 'w'
    ...
    window.addEventListener('keypress', function(e){
        var isKey = e.key === scriptToggleKey
        var validTarget = (
        ...
```

```js
    scriptToggleKey = 'Escape'
    ...
    window.addEventListener('keyup', function(e){
        var isKey = e.key === scriptToggleKey
        var validTarget = (

```

**Comment by leadra** [comment]
成功了!!
原來按鍵的屬性也不同啊..學到了
感謝你~也不好意思~因為之前用的腳本Maximize Video導致習慣，H5通用的
但是您的專用腳本，速度快又順，有針對性。
