### ISSUE TITLE
[bug] Theater mode carries over to search page if you go back.

### ISSUE THREAD

**Issue by USForeignPolicy** [Zren/ResizeYoutubePlayerToWindowSize#76]
If you search for something,
Click on a video, and then click go back.

You are left with this giant whitespace where nothing is placed, 
it appears to me as if it is like the theater mode is carried over to the search results.

Here are some Crude methods ive implemented to get around this

First is just simply a function that reloads anytime a Popstate event occurs.
So if we hit the back-button, the page will refresh.
`window.addEventListener('popstate', function(event) {
  location.reload();
});
`

Another is if we want to reload between youtube videos we click on we can do:

`let previousUrl = window.location.href;
setInterval(function() {
  if (window.location.href !== previousUrl) {
    location.reload();
  }
  previousUrl = window.location.href;
}, 1000); // Check every 1 second`

![1](https://user-images.githubusercontent.com/64338456/228666980-c593a171-0e3c-4e52-98fc-257dcd7e13d7.PNG)
![2](https://user-images.githubusercontent.com/64338456/228666981-36bc6dfe-9a45-4ba8-b34a-0f1c180b5033.PNG)

**Comment by Zren** [comment]
Ah. Seems that youtube fires a `yt-navigate-finish` event, but doesn't fire a `yt-navigate-start` when you use the browser's back button.

```js
        window.addEventListener('yt-navigate-start', function(e) {
            console.log('yt-navigate-start', e)
            console.log('window.location.href', window.location.href)
            ytwp.materialPageTransition()
        })
        window.addEventListener('yt-navigate-finish', function(e) {
            console.log('yt-navigate-finish', e)
            console.log('window.location.href', window.location.href)
        })
```

I need to test with a faster computer and chromium to make sure that moving it to `yt-navigate-finish` doesn't cause a lag.

**Comment by USForeignPolicy** [comment]
> Ah. Seems that youtube fires a `yt-navigate-finish` event, but doesn't fire a `yt-navigate-start` when you use the browser's back button.
> 
> ```js
>         window.addEventListener('yt-navigate-start', function(e) {
>             console.log('yt-navigate-start', e)
>             console.log('window.location.href', window.location.href)
>             ytwp.materialPageTransition()
>         })
>         window.addEventListener('yt-navigate-finish', function(e) {
>             console.log('yt-navigate-finish', e)
>             console.log('window.location.href', window.location.href)
>         })
> ```
> 
> I need to test with a faster computer and chromium to make sure that moving it to `yt-navigate-finish` doesn't cause a lag.

I will test on chromium-freeworld the next few days, and then on a windows machine once I get back from work trip.

Thanks for the quick fix. :)

**Comment by Zren** [comment]
I decided to bind to `yt-page-data-fetched` which also seems to fire every time. It is also bound to `yt-navigate-finish` too just in case though.
