### ISSUE TITLE
Possible New Layout Being Tested

### ISSUE THREAD

**Issue by Zren** [Zren/ResizeYoutubePlayerToWindowSize#81]
> I would love to help, but YouTube has updated the UI but the update does not show up in Incognito. This is the new UI I see:

![image](https://github.com/Zren/ResizeYoutubePlayerToWindowSize/assets/82726788/3186554d-13b7-498f-be96-e8d4d90d9ad3)

> Weird thing is I only see this on this one single account but any other youtube account shows the original interface so I guess it's not that important right now.

_Originally posted by @evkaw in https://github.com/Zren/ResizeYoutubePlayerToWindowSize/issues/79#issuecomment-1699526687_

**Comment by Zren** [comment]
@evkaw: I'm assuming you didn't have ResizeYT enabled when you ran that script. I've since edited the code to run without the script enabled:

```js
function debugPage() {
        function prettyHtml(el) {
            var s = el.outerHTML
            return s.substr(0, s.indexOf('>')+1)
        }
        var defStyle = {
            'display':'block', 'position': 'static',
            'left': 'auto', 'right': 'auto', 'top': 'auto', 'bottom': 'auto',
            'padding-left':'0px', 'padding-right':'0px', 'padding-top':'0px', 'padding-bottom':'0px',
            'margin-left':'0px', 'margin-right':'0px', 'margin-top':'0px', 'margin-bottom':'0px',
            'width': 'auto', 'min-width': 'auto', 'max-width': 'auto',
            'height': 'auto', 'min-height': 'auto', 'max-height': 'auto',
        }
        var keyFilter = Object.keys(defStyle)
        var node = document.querySelector('#movie_player video')
        var outStr = ''
        while (node && node.parentNode) {
            var style = getComputedStyle(node)
            var styleDiff = {}
            for (var key of style) {
                if (keyFilter.includes(key) && style[key] != defStyle[key]) {
                    styleDiff[key] = style[key]
                }
            }
            outStr += prettyHtml(node) + ' ' + JSON.stringify(styleDiff) + '\n'
            node = node.parentNode
        }
        outStr = outStr.split('\n').reverse().join('\n')
        console.log('debugPage', outStr)
    }
    debugPage()
```

**Comment by evkaw** [comment]
Oops, that's my bad, I should have done that. Will be sending you the output

**Comment by Zren** [comment]
Seems that it's been renamed from `ytd-watch-flexy` to `ytd-watch-grid`. I'll try adding a few more rules to fix that up.


Mine:

```css
html
body
ytd-app
#content
ytd-page-manager#page-manager
ytd-watch-flexy#ytd-page-manager
#full-bleed-container
#player-full-bleed-container
#player-container
ytd-player#ytd-player
#container.ytd-player
.html5-video-player
.html5-video-container
video.html5-main-video
```

Yours:
```css
html
body
ytd-app
#content.ytd-app
ytd-page-manager#page-manager.ytd-app
ytd-watch-grid#ytd-page-manager
#player-full-bleed-container.ytd-watch-grid
#player-container.ytd-watch-grid
ytd-player#ytd-player.ytd-watch-grid
#container.ytd-player
.html5-video-player
.html5-video-container
video.html5-main-video
```

```diff
diff --git a/YTLayoutMe.txt b/YTLayoutJA.txt
index d6d97ab..6bad7f0 100644
--- a/YTLayoutMe.txt
+++ b/YTLayoutJA.txt
@@ -3,11 +3,10 @@ body
 ytd-app
 #content.ytd-app
 ytd-page-manager#page-manager.ytd-app
-ytd-watch-flexy#ytd-page-manager
-#full-bleed-container.ytd-watch-flexy
-#player-full-bleed-container.ytd-watch-flexy
-#player-container.ytd-watch-flexy
-ytd-player#ytd-player.ytd-watch-flexy
+ytd-watch-grid#ytd-page-manager
+#player-full-bleed-container.ytd-watch-grid
+#player-container.ytd-watch-grid
+ytd-player#ytd-player.ytd-watch-grid
 #container.ytd-player
 .html5-video-player
 .html5-video-container
```

**Comment by evkaw** [comment]
That's really interesting, also completely unrelated, I use a chrome extension called Migaku and it shows the captions of the video I'm currently watching as a sidebar on screen. Anyhow, the extension is displayed over the video (blocking that margin of it) compared to the original layout which is below. Don't know if this is of fault of the userscript but if you have any time I would love if you could check it out. 
<img width="1474" alt="Screenshot 2023-08-30 at 22 23 36@2x" src="https://github.com/Zren/ResizeYoutubePlayerToWindowSize/assets/82726788/e095450f-579e-41d9-bfa7-8112266f9e80">

**Comment by Zren** [comment]
A added a couple CSS styles for `ytd-watch-grid`. Let me know if it works for you. There's a good chance it won't as there's been many changes to the layout.

**Comment by evkaw** [comment]
Works as expected in theater mode with some bugs down in the context menu:

<img width="1496" alt="Screenshot 2023-08-30 at 22 54 10@2x" src="https://github.com/Zren/ResizeYoutubePlayerToWindowSize/assets/82726788/3a9e830d-88d8-4fc3-8c91-6cc2d2de39b4">
<img width="1495" alt="Screenshot 2023-08-30 at 22 54 29@2x" src="https://github.com/Zren/ResizeYoutubePlayerToWindowSize/assets/82726788/a28e97ff-cd57-4b0f-b4da-845f0b4e647b">

Although it looks like this on the normal layout:
<img width="1502" alt="Screenshot 2023-08-30 at 22 54 45@2x" src="https://github.com/Zren/ResizeYoutubePlayerToWindowSize/assets/82726788/b784c832-2de8-4b1b-8e1a-06e6124c501b">
<img width="1490" alt="Screenshot 2023-08-30 at 22 55 15@2x" src="https://github.com/Zren/ResizeYoutubePlayerToWindowSize/assets/82726788/b2fd9cb8-1a05-43b5-b36b-028902b22075">

**Comment by Zren** [comment]
The script isn't suppose to work in normal layout (it auto-clicks the theater mode button).

As for the minor papercuts (title under Youtube logo), you'll have to wait until I can see it to fix them as it's probably a more complicated fix.

**Comment by Zren** [comment]
Actually, now that I know it mostly works in v135, I went back and `Ctrl+F` for `ytd-watch-flexy` and copied the CSS rules for `ytd-watch-grid`.

Does v136 work better?

**Comment by evkaw** [comment]
yea! working perfectly now, thank you
